"""
config.py — App-level configuration for MediScan AI
Only application settings live here (file limits, UI, disclaimer etc.)

LLM / model setup lives in models/models.py — not here.
That keeps the separation clean, exactly like your Deep Research project.
"""

import os
from dotenv import load_dotenv

load_dotenv(override=True)


# ─────────────────────────────────────────────
#  File Upload Settings
# ─────────────────────────────────────────────

MAX_FILE_SIZE_MB: int = int(os.getenv("MAX_FILE_SIZE_MB", "10"))
MAX_FILE_SIZE_BYTES: int = MAX_FILE_SIZE_MB * 1024 * 1024
ALLOWED_EXTENSIONS: list[str] = [".pdf", ".docx", ".doc"]


# ─────────────────────────────────────────────
#  App Settings
# ─────────────────────────────────────────────

APP_ENV: str = os.environ.get("APP_ENV", "development")
IS_DEVELOPMENT: bool = APP_ENV == "development"

GRADIO_SERVER_PORT: int = int(os.environ.get("GRADIO_SERVER_PORT", "7860"))
GRADIO_SHARE: bool = os.environ.get("GRADIO_SHARE", "False").lower() == "true"

APP_TITLE: str = "MediScan AI"
APP_SUBTITLE: str = "Intelligent Medical Report Analyzer"
APP_VERSION: str = "1.0.0 RC1"


# ─────────────────────────────────────────────
#  Medical Disclaimer
# ─────────────────────────────────────────────

MEDICAL_DISCLAIMER: str = (
    "⚠️ IMPORTANT DISCLAIMER: This analysis is generated by an AI system and is intended "
    "for informational and educational purposes only. It does NOT constitute professional "
    "medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider "
    "regarding any medical conditions, test results, or health concerns. "
    "In case of a medical emergency, contact emergency services immediately."
)


# ─────────────────────────────────────────────
#  Validation
# ─────────────────────────────────────────────

def validate_config() -> tuple[bool, list[str]]:
    """
    Validates required environment variables are present.
    Returns (is_valid, list_of_errors).
    Called at startup in test_connectivity.py and app.py.
    """
    errors = []

    if not os.environ.get("GITHUB_API_KEY"):
        errors.append(
            "GITHUB_API_KEY is not set. "
            "Add it to your .env file. "
            "Get one at: github.com → Settings → Developer settings → Personal access tokens"
        )

    return (len(errors) == 0), errors


if __name__ == "__main__":
    is_valid, errors = validate_config()
    if is_valid:
        print("✅ Config valid")
        print(f"   App      : {APP_TITLE} {APP_VERSION}")
        print(f"   Env      : {APP_ENV}")
        print(f"   Max file : {MAX_FILE_SIZE_MB}MB")
        print(f"   Port     : {GRADIO_SERVER_PORT}")
    else:
        print("❌ Config errors:")
        for err in errors:
            print(f"   → {err}")
