"""
tools/recommendation_generator.py — Recommendation Agent for MediScan AI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 
PURPOSE:
    This is Tool 3 in the agentic pipeline — the second real LLM call.
    It takes the ReportFindings produced by report_analyzer.py (Week 3)
    and generates personalized health recommendations.
 
    Pipeline position:
        parse_document()        ← Week 2 (document_parser.py)
            ↓
        analyze_report_text()   ← Week 3 (report_analyzer.py)
            ↓ ReportFindings
        generate_recommendations() ← Week 4 (THIS FILE)
            ↓ ReportRecommendations
        app.py display          ← Recommendations tab populated
 
HOW IT DIFFERS FROM THE ANALYZER AGENT:
 
    report_analyzer_agent:
    — Input:  raw extracted text from the PDF
    — Output: structured extraction of WHAT IS IN the report
    — Temperature: 0.1 (very low — extraction must be precise)
    — Task: extraction and classification
 
    recommendation_agent:
    — Input:  structured findings summary (from ReportFindings)
    — Output: personalized advice DERIVED from those findings
    — Temperature: 0.3 (slightly higher — advice benefits from natural language)
    — Task: interpretation and advice generation
 
    This separation means each agent does ONE thing well.
    The recommendation agent never sees the raw PDF text — it only
    sees the clean structured findings. This keeps it focused.
 
INPUT PREPARATION — _format_findings_for_recommendation():
    We don't pass the full ReportFindings JSON to the LLM because it
    contains a lot of normal values that don't need recommendations.
    Instead we format a focused summary that highlights:
    — All abnormal/borderline findings (highest priority)
    — Patient context (age, gender — for personalization)
    — All lab values with their flags (for completeness)
    This reduces tokens and improves recommendation focus.
"""

import logging
from agents import Agent, Runner, ModelSettings, result
from dotenv.main import logger
from models.models import github_model
from custom_data_types import (
    ReportFindings, 
    ReportRecommendations,
    DietaryRecommendation,
    LifestyleModification,
    FollowUpAction
)
from prompts.recommendation_prompt import (
    RECOMMENDATION_SYSTEM_PROMPT,
    build_recommendation_user_message
)

logger = logging.getLogger("recommendation_generator")

# ── Canonical disclaimer — always injected AFTER the LLM call ─
# The LLM receives this field in the schema and writes its own
# version. We overwrite it here unconditionally so the test and
# the UI always see the exact string defined by the product.
# This is the correct pattern: let the model fill content fields;
# enforce fixed strings in code, not in prompts.

_DISCLAIMER = (
    "These recommendations are generated by an AI system for "
    "informational and educational purposes only. They do NOT "
    "constitute professional medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare provider before making "
    "any changes to your diet, lifestyle, or medical care."
)

# ─────────────────────────────────────────────────────────────
#  recommendation_agent — defined at module level
#
#  WHY output_type=ReportRecommendations?
#  The SDK converts ReportRecommendations to JSON schema and adds
#  it to the system prompt. The LLM must respond with valid JSON
#  matching that schema — giving us a validated Python object back.
#
#  WHY temperature=0.3?
#  Slightly higher than the analyzer (0.1) because recommendations
#  benefit from more natural, warm language. But still low enough
#  to be consistent and not hallucinate medical facts.
# ─────────────────────────────────────────────────────────────

recommendation_agent = Agent(
    name="Recommendation Agent",
    instructions=RECOMMENDATION_SYSTEM_PROMPT,
    output_type=ReportRecommendations,
    model=github_model,
    model_settings=ModelSettings(temperature=0.3)
)

# ─────────────────────────────────────────────────────────────
#  _format_findings_for_recommendation()  — private helper
#
#  WHY FORMAT FINDINGS INSTEAD OF PASSING RAW JSON?
#  We could pass findings.model_dump_json() directly to the LLM.
#  But that includes a lot of verbose Pydantic structure and normal
#  values that need no recommendations. A focused, human-readable
#  summary is easier for the LLM to reason about, produces better
#  recommendations, and uses fewer tokens.
#
#  The format we produce:
#  1. Patient context (age, gender)
#  2. Abnormal flags section (most important — processed first)
#  3. All lab values with flag status
#  4. Clinical summary from the analyzer
# ─────────────────────────────────────────────────────────────

def _format_findings_for_recommendation(findings: ReportFindings) -> str:
    """
    Format ReportFindings into a focused text summary for the
    recommendation agent. Highlights abnormal findings first.
 
    Args:
        findings: The ReportFindings object from analyze_report_text()
 
    Returns:
        Formatted string ready to be embedded in the user message.
    """
    lines:list[str] = []

    # ── Report type ───────────────────────────────────────────
    lines.append(f"REPORT TYPE: {findings.report_type.replace('_', ' ').upper()}")
    lines.append("")

    # ── Patient context ───────────────────────────────────────
    ctx = findings.patient_context
    lines.append("PATIENT INFORMATION:")
    lines.append(f"Age: {ctx.age or 'Not specified'}")
    lines.append(f"Gender: {ctx.gender or 'Not specified'}")
    lines.append(f"Date: {ctx.report_date or 'Not specified'}")

    # ── Abnormal flags (most important — listed first) ────────
    if findings.abnormal_flags:
        lines.append("ABNORMAL FINDINGS (requires recommendations):")
        for flag in findings.abnormal_flags:
            lines.append(
                f"  [{flag.severity.upper()}] {flag.finding}"
                f"(category: {flag.category})"
            )
        lines.append("")
    else:
        lines.append("ABNORMAL FINDINGS: None - all values within normal range")
        lines.append("")

    # ── All lab values with flags ─────────────────────────────
    if findings.lab_values:
        lines.append("ALL LAB VALUES:")
        # Group by flag status — abnormal first
        abnormal = [ lv for lv in findings.lab_values if lv.flag != "Normal"]
        normal = [ lv for lv in findings.lab_values if lv.flag == "Normal"]

        if abnormal:
            lines.append("  Abnormal/Borderline:")
            for lv in abnormal:
                note = f" - {lv.clinical_note}" if lv.clinical_note else ""
                lines.append(
                    f"  • {lv.parameter}: {lv.value} "
                    f"(ref: {lv.reference_range}) [{lv.flag}]{note}"
                )

        if normal:
            lines.append("  Normal (no recommendation needed unless otherwise needed):")
            for lv in normal:
                lines.append(
                    f"  • {lv.parameter}: {lv.value} "
                    f"(ref: {lv.reference_range}) [Normal]"
                )
        lines.append("")

    # ── Clinical summary from analyzer ────────────────────────
    if findings.clinical_summary:
        lines.append("CLINICAL SUMMARY FROM ANALYZER:")
        lines.append(f"  {findings.clinical_summary}")
        lines.append("")

    # ── Medications ───────────────────────────────────────────
    if findings.medications:
        lines.append("CURRENT MEDICATIONS:")
        for med in findings.medications:
            purpose = f" - for {med.purpose}" if med.purpose else ""
            lines.append(f"  • {med.name} ({med.dosage}){purpose}")
        lines.append("")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────
#  generate_recommendations()  — MAIN PUBLIC ASYNC FUNCTION
#
#  This is what app.py calls. It's async because Runner.run()
#  is a coroutine — must be awaited.
#
#  ERROR HANDLING:
#  Like analyze_report_text(), this function never raises exceptions.
#  On failure it returns a ReportRecommendations with the error
#  message in overall_assessment so the UI always has something
#  meaningful to display.
# ─────────────────────────────────────────────────────────────

async def generate_recommendations(
    findings: ReportFindings) -> ReportRecommendations:
    """
    Run the recommendation agent on structured ReportFindings.
 
    Takes the validated findings from analyze_report_text() and
    generates personalized dietary, lifestyle, and follow-up advice.
 
    This function is async because Runner.run() is a coroutine.
    Always await this from the caller.
 
    Args:
        findings: ReportFindings from analyze_report_text()
 
    Returns:
        ReportRecommendations — always returned, never raises.
        On error: returns a ReportRecommendations with error info
        in overall_assessment.
 
    Usage in app.py (Week 5):
        recommendations = await generate_recommendations(findings)
    """

    # ── Guard: non-medical document ───────────────────────────
    # If the document isn't medical, there's nothing to recommend
    if findings.is_non_medical:
        return ReportRecommendations(
            dietary_recommendations=[],
            lifestyle_modifications=[],
            follow_up_actions=[],
            overall_urgency="routine",
            overall_assessment=(
                "The uploaded document does not appear to be a medical report. "
                "No recommendations can be generated. Please upload a lab report, "
                "clinical note, prescription, or discharge summary."
            )
        )

    # ── Guard: no abnormal findings ───────────────────────────
    # If everything is normal, generate a brief positive response
    # without making a full LLM call (saves tokens and time)
    if not findings.abnormal_flags and not findings.lab_values:
        return ReportRecommendations(
            dietary_recommendations=[],
            lifestyle_modifications=[],
            follow_up_actions=[
                FollowUpAction(
                    action="Continue with routine health check-ups as recommended by your physician.",
                    timeframe="At your next scheduled check-up",
                    urgency="routine",
                    specialist="General Physician / Primary Care",
                )
            ],
            overall_urgency="routine",
            overall_assessment=(
                "No lab values or abnormal findings were extracted from this report. "
                "If you believe this is an error, please check the Raw Text tab to "
                "confirm the document was parsed correctly."
            )
        )

    # ── Step 1: Format findings for the recommendation agent ──
    # Convert ReportFindings → focused text summary
    findings_summary = _format_findings_for_recommendation(findings)

    logger.info(
        f"Generating recommendations | "
        f"abnormal_flags={len(findings.abnormal_flags)} | "
        f"lab_values={len(findings.lab_values)} | "
        f"age={findings.patient_context.age} | "
        f"gender={findings.patient_context.gender}"
    )

    # ── Step 2: Build the user message ───────────────────────
    user_message = build_recommendation_user_message(
        findings_summary=findings_summary,
        patient_age=findings.patient_context.age,
        patient_gender=findings.patient_context.gender
    )

    # ── Step 3: Run the recommendation agent ─────────────────
    # Same pattern as your Deep Research writer_agent:
    #   result = await Runner.run(agent, message)
    #   output = result.final_output_as(OutputType)

    try:
        logger.info("Calling recommendation_agent via Runner.run()...")

        result = await Runner.run(
            recommendation_agent,
            user_message
        )

        recommendations: ReportRecommendations = result.final_output_as(
            ReportRecommendations
        )

        # Always overwrite — the LLM writes its own disclaimer text
        # regardless of the schema default. We enforce the canonical
        # product disclaimer in code, not in the prompt.
        recommendations.disclaimer = _DISCLAIMER

        logger.info(
            f"Recommendations complete | "
            f"dietary={len(recommendations.dietary_recommendations)} | "
            f"lifestyle={len(recommendations.lifestyle_modifications)} | "
            f"follow_up={len(recommendations.follow_up_actions)} | "
            f"urgency={recommendations.overall_urgency}"
        )

        return recommendations

    except Exception as e:
        logger.error(f"Recommendation agent failed: {e}")
        return ReportRecommendations(
            dietary_recommendations=[],
            lifestyle_modifications=[],
            follow_up_actions=[],
            overall_urgency="routine",
            overall_assessment=(
                f"⚠️ Recommendations could not be generated due to an API error: "
                f"{str(e)[:200]}. "
                f"Please try again. Your findings were extracted successfully — "
                f"only the recommendations step failed."
            )
        )

# ─────────────────────────────────────────────────────────────
#  format_recommendations_for_display()  — UI renderer
#
#  Converts a ReportRecommendations object into rich markdown
#  for display in the Gradio "Recommendations" tab.
#
#  URGENCY COLOUR MAPPING:
#  routine         → ✅ green  (no rush)
#  consult_soon    → 🟡 yellow (within 2-4 weeks)
#  urgent          → 🟠 orange (within 1 week)
#  seek_immediate  → 🚨 red    (go today)
#
#  PRIORITY COLOUR MAPPING (dietary/lifestyle):
#  high   → 🔴 (important, start now)
#  medium → 🟡 (implement soon)
#  low    → 🟢 (general wellness)
# ─────────────────────────────────────────────────────────────

URGENCY_DISPLAY: dict[str, str] = {
    "routine":             "✅ Routine — Review at your next scheduled check-up",
    "consult_soon":        "🟡 Consult Soon — See your physician within 2-4 weeks",
    "urgent":              "🟠 Urgent — See your physician within 1 week",
    "seek_immediate_care": "🚨 Seek Immediate Care — Contact your doctor today",
}
 
PRIORITY_EMOJI: dict[str, str] = {
    "high":   "🔴",
    "medium": "🟡",
    "low":    "🟢",
}
 
URGENCY_EMOJI: dict[str, str] = {
    "routine":   "✅",
    "soon":      "🟡",
    "urgent":    "🟠",
    "immediate": "🚨",
}

def format_recommendations_for_display(recs = ReportRecommendations) -> str:
    """
    Convert a ReportRecommendations object into markdown for
    the Gradio Recommendations tab.
 
    Args:
        recs: A ReportRecommendations object from generate_recommendations()
 
    Returns:
        Markdown string ready to display in gr.Markdown()
    """
    lines: list[str] = []
 
    # ── Overall urgency banner ────────────────────────────────
    urgency_text = URGENCY_DISPLAY.get(
        recs.overall_urgency,
        f"⚠️ {recs.overall_urgency}"
    )
    lines += [
        "## 💡 Personalized Recommendations",
        "",
        f"### ⚡ Overall Assessment",
        "",
        f"**{urgency_text}**",
        "",
        recs.overall_assessment,
        "",
        "---",
        "",
    ]
 
    # ── Dietary recommendations ───────────────────────────────
    if recs.dietary_recommendations:
        lines += ["### 🥗 Dietary Recommendations", ""]
 
        for i, diet in enumerate(recs.dietary_recommendations, 1):
            priority_icon = PRIORITY_EMOJI.get(diet.priority, "🟡")
            lines += [
                f"**{priority_icon} {i}. {diet.suggestion}**",
                "",
                f"*Why:* {diet.reason}",
                "",
            ]
            if diet.foods_to_increase:
                foods = ", ".join(diet.foods_to_increase)
                lines.append(f"✅ **Increase:** {foods}")
            if diet.foods_to_avoid:
                foods = ", ".join(diet.foods_to_avoid)
                lines.append(f"❌ **Reduce/Avoid:** {foods}")
            lines.append("")
 
    # ── Lifestyle modifications ───────────────────────────────
    if recs.lifestyle_modifications:
        lines += ["### 🏃 Lifestyle Modifications", ""]
 
        for i, lifestyle in enumerate(recs.lifestyle_modifications, 1):
            priority_icon = PRIORITY_EMOJI.get(lifestyle.priority, "🟡")
            lines += [
                f"**{priority_icon} {i}. {lifestyle.modification}**",
                "",
                f"*Why:* {lifestyle.reason}",
                f"*Category:* {lifestyle.category.title()}",
                "",
            ]
 
    # ── Follow-up actions ─────────────────────────────────────
    if recs.follow_up_actions:
        lines += ["### 📅 Follow-Up Actions", ""]
 
        for i, action in enumerate(recs.follow_up_actions, 1):
            urgency_icon = URGENCY_EMOJI.get(action.urgency, "🟡")
            specialist = f" → {action.specialist}" if action.specialist else ""
            lines += [
                f"**{urgency_icon} {i}. {action.action}**",
                "",
                f"*When:* {action.timeframe}{specialist}",
                "",
            ]
 
    # ── Disclaimer ────────────────────────────────────────────
    lines += [
        "---",
        f"*⚠️ {recs.disclaimer}*",
        "",
        "*Generated by MediScan AI · openai/gpt-4.1-mini via AI Models*",
    ]
 
    return "\n".join(lines)
 
